# Generated by Django 4.2.13 on 2024-05-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, null=True)),
                ('tax', models.FloatField(default=0.0)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
