# Generated by Django 4.2.13 on 2024-05-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_food_product',
            field=models.BooleanField(default=False),
        ),
    ]
